sudo: false
addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-3.9
                        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
                        - boost-latest
                packages:
                        - cmake
                        - cmake-data
                        - gcc-5
                        - g++-5
                        - clang-3.9
                        - libboost1.55-all-dev


language: cpp

install:
        - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
        - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi

before_script:
        - mkdir build
        - cd build

script:
        - cmake ..
        - make

after_failure:
        - cat CMakeFiles/*.log

compiler:
        - clang++
        - g++
