######################################################################
# Automatically generated by qmake (3.0) wt. maj 30 19:27:32 2017
######################################################################

QT += testlib
TEMPLATE = app
TARGET = Tests
INCLUDEPATH +=  . \
                ../Model/ \
                /usr/include/boost/
DEPENDPATH += $${INCLUDEPATH}
HEADERS += ../Model/*.h \
    tst_playertests.h \
    tst_gametests.h
SOURCES += ../Model/*.cpp \
    maintestrunner.cpp \
    tst_playertests.cpp \
    tst_gametests.cpp

QMAKE_CXXFLAGS += -std=c++11
LIBS += -L/usr/include/boost -lboost_serialization

